package com.eduaid.model;

import java.sql.Date;
import java.sql.Timestamp;

/**
 * User - Model class representing a row in the `users` table.
 *
 * Roles:  ADMIN | DONOR | RECIPIENT
 * Status: PENDING | APPROVED | DISABLED
 *
 * Follows JavaBean conventions (private fields, public getters/setters).
 * Used across DAO, Service, and Controller layers.
 */
public class User {

    // ---------------------------------------------------------------
    // Fields (mirroring database columns)
    // ---------------------------------------------------------------
    private int       userId;
    private String    fullName;
    private String    email;
    private String    phone;
    private String    passwordHash;   // SHA-256 hash – never the plain password
    private String    role;           // ADMIN | DONOR | RECIPIENT
    private String    status;         // PENDING | APPROVED | DISABLED
    private Date      dob;
    private String    address;
    private String    institution;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    // ---------------------------------------------------------------
    // Constructors
    // ---------------------------------------------------------------

    /** Default constructor (required for JavaBean compliance). */
    public User() {}

    /**
     * Constructor for creating a new user (registration).
     * userId, createdAt and updatedAt are auto-generated by the DB.
     */
    public User(String fullName, String email, String phone,
                String passwordHash, String role,
                Date dob, String address, String institution) {
        this.fullName    = fullName;
        this.email       = email;
        this.phone       = phone;
        this.passwordHash = passwordHash;
        this.role        = role;
        this.status      = "PENDING"; // default: awaits admin approval
        this.dob         = dob;
        this.address     = address;
        this.institution = institution;
    }

    // ---------------------------------------------------------------
    // Getters & Setters
    // ---------------------------------------------------------------

    public int getUserId()               { return userId; }
    public void setUserId(int userId)    { this.userId = userId; }

    public String getFullName()                  { return fullName; }
    public void   setFullName(String fullName)   { this.fullName = fullName; }

    public String getEmail()               { return email; }
    public void   setEmail(String email)   { this.email = email; }

    public String getPhone()               { return phone; }
    public void   setPhone(String phone)   { this.phone = phone; }

    public String getPasswordHash()                      { return passwordHash; }
    public void   setPasswordHash(String passwordHash)   { this.passwordHash = passwordHash; }

    public String getRole()              { return role; }
    public void   setRole(String role)   { this.role = role; }

    public String getStatus()                { return status; }
    public void   setStatus(String status)   { this.status = status; }

    public Date getDob()           { return dob; }
    public void setDob(Date dob)   { this.dob = dob; }

    public String getAddress()                 { return address; }
    public void   setAddress(String address)   { this.address = address; }

    public String getInstitution()                     { return institution; }
    public void   setInstitution(String institution)   { this.institution = institution; }

    public Timestamp getCreatedAt()                    { return createdAt; }
    public void      setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    public Timestamp getUpdatedAt()                    { return updatedAt; }
    public void      setUpdatedAt(Timestamp updatedAt) { this.updatedAt = updatedAt; }

    // ---------------------------------------------------------------
    // Convenience / role-check methods
    // ---------------------------------------------------------------

    /** Returns true if the user has the ADMIN role. */
    public boolean isAdmin()     { return "ADMIN".equals(role); }

    /** Returns true if the user has the DONOR role. */
    public boolean isDonor()     { return "DONOR".equals(role); }

    /** Returns true if the user has the RECIPIENT role. */
    public boolean isRecipient() { return "RECIPIENT".equals(role); }

    /** Returns true if the user account has been approved by admin. */
    public boolean isApproved()  { return "APPROVED".equals(status); }

    /** Returns true if the account is still awaiting admin approval. */
    public boolean isPending()   { return "PENDING".equals(status); }

    @Override
    public String toString() {
        return "User{userId=" + userId
             + ", fullName='" + fullName + '\''
             + ", email='" + email + '\''
             + ", role='" + role + '\''
             + ", status='" + status + '\'' + '}';
    }
}
